### PR TITLE
CI: include PHP 8.0, 8.1 and 8.2

### PR DESCRIPTION
**Pull request by k00ni**
With this PR all PHP versions are covered.

### CODE REVIEW

**Comment by lanthaler** [comment]
This will require updating PHPUnit as the current version isn't compatible with PHP 8, see https://github.com/lanthaler/JsonLD/actions/runs/3149070407/jobs/5121655856

**Comment by k00ni** [comment]
What is your opinion on discarding PHP EOL releases?

PHP below 7.4 is end of life, https://www.php.net/supported-versions.php.

**Comment by lanthaler** [comment]
Shared hosters are usually quite slow in upgrading to new PHP versions so unless there's a good reason to deprecate support I'd rather not do that. I started to look into PHP 8 support in [this branch](https://github.com/lanthaler/JsonLD/tree/php8)

**Comment by k00ni** [comment]
OK.

**Comment by lanthaler** [comment]
If you are interested, I'd definitely appreciate help on this

**Comment by k00ni** [comment]
> Shared hosters are usually quite slow in upgrading to new PHP versions so unless there's a good reason to deprecate support I'd rather not do that.

Supporting PHP 5.x until 8.1 is gonna be hard, because there is a wide range of changes required (from PHPUnit to API changes like return values etc.). My main reason against it would be **our time and resource limitation**. I can only speak for myself here, but I would not invest time in maintaining PHP versions, which are marked as "end of life" for years.

I would suggest some middle ground here: Keep JsonLD as it is in a 1.x branch and create a 2.x branch to support PHP 7.1+ (or something like that). 1.x should be communicated as legacy code but maintained, but further changes and improvements will land only in 2.x.

WDYT?

**Pull request closed without merging**
