### PR TITLE
Rename Object to JsonLDObject (Fix PHP 7.2)

### PR DESCRIPTION
**Pull request by whikloj**
Similar to #79 but doesn't switch back to use `stdClass()` but instead changes the old `Object` name to `JsonLDObject`. Also fixes two locations where arrays were assumed for uses of `count()` but tests fail.

This is also starting to hit the limits of using PHPUnit 4, I'd recommend dropping some of the older versions of PHP from the support matrix.

### CODE REVIEW

**Comment by whikloj** [comment]
Of interest to @acoburn and @DiegoPino

**Comment by whikloj** [comment]
@lanthaler If there is something I can do to make this easier, please let me know. I realize that you may not want to use `JsonLDObject` and I have no issue changing that if it helps you.

**Comment by rdewaele** [comment]
We also encountered this problem while using api-platform with this plugin to generate the PHP classes.
@lanthaler Could you share an update on reviewing and/or merging this PR?

**Comment by Mehrdad-Dadkhah** [comment]
same problem, please merge this PR

**Comment by whikloj** [comment]
Hi @lanthaler,

6 months in and there has been no response on this PR. Is there something I can do to help move this forward?

**Comment by DiegoPino** [comment]
@lanthaler I know you are very busy dealing with JSON-LD 1.1 specs and your day job too, but it would mean a great deal to us == highly appreciated == if you could review/merge this pull. Many of us are using this package (great on one) current and future larger community-driven Open Source projects and having PHP 7.2 support is crucial. Thanks!

**Comment by osma** [comment]
Yay, finally! Thanks a lot @lanthaler!

**Comment by DiegoPino** [comment]
@lanthaler++ thanks a lot

**Comment by whikloj** [comment]
Thank you @lanthaler, I would have been happy to make the desired changes but either way I am glad to get this working. Cheers.

**Comment by lanthaler** [comment]
No worries. I had a couple of hours and wanted to get as much done as possible :-)
Thanks for the PR and the patience

**Pull request merged**
